# Generated by Django 5.2.7 on 2025-10-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_template", models.CharField(max_length=100, unique=True)),
                ("oggetto", models.CharField(max_length=255)),
                (
                    "corpo",
                    models.TextField(
                        help_text="Puoi usare placeholders come {{nome}} e {{cognome}}."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Template Email",
            },
        ),
    ]
