# Generated by Django 5.2.7 on 2025-10-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0002_emailtemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contatto",
            name="ruolo",
        ),
        migrations.RemoveField(
            model_name="contatto",
            name="associazione",
        ),
        migrations.AlterField(
            model_name="contatto",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name="Ruolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_ruolo",
                    models.CharField(
                        help_text="Il nome del ruolo specifico per l'associazione.",
                        max_length=100,
                    ),
                ),
                (
                    "associazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruoli",
                        to="gestione.associazione",
                    ),
                ),
                (
                    "contatti",
                    models.ManyToManyField(
                        blank=True, related_name="ruoli", to="gestione.contatto"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ruoli",
                "unique_together": {("associazione", "nome_ruolo")},
            },
        ),
        migrations.DeleteModel(
            name="RuoloReferente",
        ),
    ]
